variables:
#  - group: hpoc-prism-central
  - group: demo-cluster

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - windows/*

schedules:
- cron: "0 1 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - main
  always: true

pool:

  name: default

steps:

- task: CopyFiles@2

  displayName: 'Copy Packer Files to Artifacts'

  inputs:

    SourceFolder: windows

    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true

- task: CmdLine@2
  displayName: 'Validate Build'
  inputs:
    script: 'echo $(PKR_VAR_PC_USER)'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

- task: CmdLine@2
  displayName: 'Validate Build'
  inputs:
    script: 'packer validate .'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

- task: CmdLine@2
  displayName: 'Building Image'
  inputs:
    script: 'packer build .'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
