trigger:
  branches:
    include:
    - main
  paths:
    include:
    - windows/*

schedules:
- cron: "0 1 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - main
  always: true

pool:

  name: default

steps:

- task: CopyFiles@2

  displayName: 'Copy Packer Files to Artifacts'

  inputs:

    SourceFolder: windows

    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true

- task: Bash@3
  inputs:
    filePath: '$(Build.ArtifactStagingDirectory)/packer'
    arguments: 'validate .'