# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: 0.1.$(Rev:r)

variables:
#  - group: hpoc-prism-central
  - group: demo-cluster

trigger:
  - main

pool: 'default'

stages:

- stage: Deploy
  jobs:
  - deployment: CreateImage
    displayName: 'Create Image'
    container:
      image: hashicorp/packer:latest
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          
          - script: |
              validate .